### ISSUE TITLE
Playbook with ids with mix case

### ISSUE THREAD

**Issue by jorgego11** [IBM-Blockchain/ansible-examples#11]
Running the playbook with ids with mix case gets:

TASK [ibm.blockchain_platform_manager : Get certificate authority] ******************************************************************************
fatal: [localhost]: FAILED! => {"access_control_allow_origin": "*", "access_control_expose_headers": "Location", "cache_control": "no-store", "changed": false, "connection": "close", "content": "{\"error\":\"not_found\",\"reason\":\"missing\",\"statusCode\":404}", "content_length": "57", "content_security_policy": "default-src 'self'", "content_type": "application/json; charset=utf-8", "date": "Wed, 15 Jan 2020 17:09:38 GMT", "elapsed": 0, "etag": "W/\"39-hP6MgPikTkJacvRXvBupCRR1L5g\"", "json": {"error": "not_found", "reason": "missing", "statusCode": 404}, "msg": "Status code was 404 and not [200]: HTTP Error 404: Not Found", "pragma": "no-cache", "redirected": false, "status": 404, "strict_transport_security": "max-age=31536000; includeSubDomains", "url": "https://4be2100df5494501b5fb610ec7f9497d-optools.uss02.blockchain.cloud.ibm.com/ak/api/v1/components/Org1CA", "vary": "Accept-Encoding", "x_content_type_options": "nosniff", "x_frame_options": "deny", "x_ratelimit_limit": "100", "x_ratelimit_remaining": "99", "x_ratelimit_reset": "1579108220", "x_xss_protection": "1; mode=block"}

After changing to all lowercase the scripts works fine

**Comment by sstone1** [comment]
Fixed in latest version of the Ansible role.
