### ISSUE TITLE
ERROR: ibm.blockchain platform manager : Get the list of components failed = 1

### ISSUE THREAD

**Issue by ArwaNashaat** [IBM-Blockchain/ansible-examples#17]
whenever I run "ansible-playbook playbook.yml" command to create the 2org-network example, I get this error. 
**"TASK [ibm.blockchain_platform_manager : Get the list of components] **************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "msg": "Status code was -1 and not [2****************]: Request failed: <urlopen error [Errno -2] Name or service not known>", "redirected": false, "status": -1, "url": "https://ibp-console.example.org:32************************/ak/api/v1/components?skip_cache=yes"}

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0"**
The os is ubuntu 18.04.3 on vmWare

**Comment by ArwaNahsaat** [comment]
changed infrastructure.type to docker, but it gave me this error **"TASK [ibm.blockchain_platform_manager : Enroll the user] ***********************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "fabric-ca-client enroll -u 'https://admin:********@localhost:18050' --caname ca -M /home/arwa/Desktop/ansible-examples/two-org-network/wallets/Org1/admin --tls.certfiles /home/arwa/Desktop/ansible-examples/two-org-network/wallets/Org1/ca-tls-root.pem", "msg": "[Errno 2] No such file or directory", "rc": 2}"**
