### ISSUE TITLE
Error while starting one-org-network

### ISSUE THREAD

**Issue by HelmiTrabelsi** [IBM-Blockchain/ansible-examples#18]
when I run the one-orh-network on localhost using docker , I get this error :

TASK [ibm.blockchain_platform_manager : Enroll the user] **************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "fabric-ca-client enroll -u 'https://admin:********@localhost:18050' --caname ca -M /home/helmi/ansible-examples/one-org-network/wallets/Org1/admin --tls.certfiles /home/helmi/ansible-examples/one-org-network/wallets/Org1/ca-tls-root.pem", "msg": "[Errno 2] Aucun fichier ou dossier de ce type: b'fabric-ca-client'", "rc": 2}

**Comment by droopygit** [comment]
Same problem for me. 

> TASK [ibm.blockchain_platform_manager : Enroll the user] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "fabric-ca-client enroll -u 'https://admin:********@localhost:18050' --caname ca -M /home/xxx/ansible-examples-master/one-org-network/wallets/Org1/admin --tls.certfiles /home/xxx/ansible-examples-master/one-org-network/wallets/Org1/ca-tls-root.pem", "msg": "[Errno 2] No such file or directory", "rc": 2}

**Comment by droopygit** [comment]
I found the problem was the path of hyperledger utilities. Check if the fabric-ca-client tool is in the current PATH.
