### ISSUE TITLE
Error while creating genesis block

### ISSUE THREAD

**Issue by AnandkKumaran** [IBM-Blockchain/ansible-examples#20]
Got this error while running ansible-playbook playbook.yml

TASK [ibm.blockchain_platform_manager : Create orderer genesis block] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["configtxgen", "-configPath", "/tmp/ansible.Ukj3J9", "-profile", "Solo", "-channelID", "testchainid", "-outputBlock", "/tmp/ansible.Ukj3J9/genesis.block"], "delta": "0:00:00.486752", "end": "2020-06-01 17:24:39.262441", "msg": "non-zero return code", "rc": 2, "start": "2020-06-01 17:24:38.775689", "stderr": "\u001b[34m2020-06-01 17:24:39.229 IST [common.tools.configtxgen] main -> INFO 001\u001b[0m Loading configuration\n\u001b[35m2020-06-01 17:24:39.258 IST [common.tools.configtxgen.localconfig] Load -> PANI 002\u001b[0m Error unmarshaling config into struct:  4 error(s) decoding:\n\n* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\n* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\n\u001b[35m2020-06-01 17:24:39.258 IST [common.tools.configtxgen] func1 -> PANI 003\u001b[0m Error unmarshaling config into struct:  4 error(s) decoding:\n\n* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\n* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\npanic: Error unmarshaling config into struct:  4 error(s) decoding:\n\n* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\n* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax [recovered]\n\tpanic: Error unmarshaling config into struct:  4 error(s) decoding:\n\n* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize\n* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\n* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax\n\ngoroutine 1 [running]:\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000123970, 0x0, 0x0, 0x0)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b2240, 0xc000231804, 0xc0001aec00, 0x1ef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc0000b2240, 0xc0001aec00, 0x1ef, 0x0, 0x0, 0x0)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79\ngithub.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000b2248, 0xc000231938, 0x1, 0x1)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x75\nmain.main.func1()\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:250 +0x1a9\npanic(0xd4fc40, 0xc0002556e0)\n\t/opt/go/go1.11.1.linux.amd64/src/runtime/panic.go:513 +0x1b9\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000123970, 0x0, 0x0, 0x0)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b2220, 0xc000231c04, 0xc0001ae400, 0x1ef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6\ngithub.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc0000b2220, 0xc0001ae400, 0x1ef, 0x0, 0x0, 0x0)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79\ngithub.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000b2228, 0xc000231d98, 0x2, 0x2)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x75\ngithub.com/hyperledger/fabric/common/tools/configtxgen/localconfig.Load(0x7ffe8e2dc1fc, 0x4, 0xc0000dff48, 0x1, 0x1, 0xc000193850)\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/localconfig/config.go:282 +0x580\nmain.main()\n\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:259 +0x616", "stderr_lines": ["\u001b[34m2020-06-01 17:24:39.229 IST [common.tools.configtxgen] main -> INFO 001\u001b[0m Loading configuration", "\u001b[35m2020-06-01 17:24:39.258 IST [common.tools.configtxgen.localconfig] Load -> PANI 002\u001b[0m Error unmarshaling config into struct:  4 error(s) decoding:", "", "* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "\u001b[35m2020-06-01 17:24:39.258 IST [common.tools.configtxgen] func1 -> PANI 003\u001b[0m Error unmarshaling config into struct:  4 error(s) decoding:", "", "* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "panic: Error unmarshaling config into struct:  4 error(s) decoding:", "", "* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax [recovered]", "\tpanic: Error unmarshaling config into struct:  4 error(s) decoding:", "", "* 'Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* 'Profiles[Solo].Orderer.EtcdRaft.Options' has invalid keys: MaxInflightBlocks, SnapshotIntervalSize", "* cannot parse 'Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "* cannot parse 'Profiles[Solo].Orderer.EtcdRaft.Options.TickInterval' as uint: strconv.ParseUint: parsing \"500ms\": invalid syntax", "", "goroutine 1 [running]:", "github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000123970, 0x0, 0x0, 0x0)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515", "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b2240, 0xc000231804, 0xc0001aec00, 0x1ef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6", "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc0000b2240, 0xc0001aec00, 0x1ef, 0x0, 0x0, 0x0)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79", "github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000b2248, 0xc000231938, 0x1, 0x1)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x75", "main.main.func1()", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:250 +0x1a9", "panic(0xd4fc40, 0xc0002556e0)", "\t/opt/go/go1.11.1.linux.amd64/src/runtime/panic.go:513 +0x1b9", "github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000123970, 0x0, 0x0, 0x0)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515", "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000b2220, 0xc000231c04, 0xc0001ae400, 0x1ef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6", "github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc0000b2220, 0xc0001ae400, 0x1ef, 0x0, 0x0, 0x0)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79", "github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000b2228, 0xc000231d98, 0x2, 0x2)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x75", "github.com/hyperledger/fabric/common/tools/configtxgen/localconfig.Load(0x7ffe8e2dc1fc, 0x4, 0xc0000dff48, 0x1, 0x1, 0xc000193850)", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/localconfig/config.go:282 +0x580", "main.main()", "\t/w/workspace/fabric-release-jobs-x86_64/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:259 +0x616"], "stdout": "", "stdout_lines": []}

**Comment by vaishnavipanchal23** [comment]
Any update on this? did this get solved?

**Comment by AnandkKumaran** [comment]
Yes, it's resolved. It's worked after updated the binaries to 1.4.7.
